version: '3.1'

services:

  db:
    build: .
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      ENV_RECREATE: no
    volumes:
       - db-data:/var/lib/postgresql/data

volumes:
  db-data:
